spring.application.name=gamestopbackend

spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce
spring.datasource.username=root
spring.datasource.password=Hnsagar@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsMyVerySecretKeyForGameStopProject2026SpringBootJWT12345
jwt.expiration=86400000
jwt.refresh-expiration=604800000
logging.level.org.springframework.security=DEBUG
logging.level.com.sg.gamestopbackend=DEBUG

# Razorpay (replace with your TEST keys from https://dashboard.razorpay.com/app/keys)
razorpay.key.id=rzp_test_TLlgKyCnH4nGwc
razorpay.key.secret=Hxe1UeZR8b5jnng5GygM7b8O
razorpay.currency=INR

# Razorpay (replace with your test keys from https://dashboard.razorpay.com/app/keys)
razorpay.key.id=rzp_test_TLlgKyCnH4nGwc
razorpay.key.secret=Hxe1UeZR8b5jnng5GygM7b8O
razorpay.currency=INR
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=4gm22cs040@gmit.ac.in
spring.mail.password=qsborvuuhnpszxku
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

